<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SonarrSource)/src/NzbDrone.Core/Sonarr.Core.csproj" />
    <Compile Include="../Shared/TestContract.cs" Link="TestContract.cs" />
    <Compile Include="../Shared/ProfileScoring.cs" Link="ProfileScoring.cs" />
  </ItemGroup>
</Project>
